---
title: "Revision notes"
author: "Arthur"
output: html_notebook
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE, warning=FALSE,fig.width = 8,fig.height = 5,fig.pos = "H" #, 
#cache.lazy = FALSE)
)
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')

library(pacman)
p_load(here)
p_load(officedown)

```



```{r LoadLibraries, include=FALSE}
source(here("RScripts","LoadInstallPackages.R"), local = knitr::knit_global())
```

```{r LoadData, include=FALSE}
source(here("RScripts","LoadAllData.R"), local = knitr::knit_global())
```

```{r ImportAllFunctions, include=FALSE}
source(here("RScripts","AllFunctions.R"), local = knitr::knit_global())
```


```{r, include=FALSE, cache=FALSE}
knitr::read_chunk(here("RScripts","MainAnalyses.R"))
# This file contains all the chunks of codes to be called at the right place in the Rmarkdown document
```



# How to estimate conditional potential outcomes

Let $Y_{ib}(t)$ be the potential outcome $(apply, access)'(Any~childcare, daycare)$  and $t \in \{C,T1,T2 \}$
we want $E(Y_ib(t)|X=x)$ where $X$ can be birth month for instance.

First let's take a look at the graphs


```{r}
ggplot(MainDB %>% filter())+stat_summary_bin(aes(y=ECSUseYes,x=BabyBirthDate,color=Assignment),bins = 20)+geom_density(aes(x=BabyBirthDate,fill=Assignment,y=..density..*100),alpha=.2)

install.packages('binsreg')

library(binsreg)


MainDB <- MainDB %>%
  mutate(RunningVar = as.numeric(difftime(BabyBirthDate, as.Date("2023-01-01"), units = "days")))
  

attach(MainDB)

binsreg(x=RunningVar,y=UseCreche, by=Assignment) 



library(rdrobust)
library(rddensity)

C <-  rdplot(x=RunningVar,y=UseCreche,subset=Assignment=="Control",title="Use Daycare, Control",kernel = "uniform",support=c(-100,100),ci=T,binselect = "qs")
T1 <- rdplot(x=RunningVar,y=UseCreche,subset=Assignment=="T1",title="Use Daycare, T1",kernel = "uniform",support=c(-100,100),binselect="qs",p=3)
T2 <- rdplot(x=RunningVar,y=UseCreche,subset=Assignment=="T2",title="Use Daycare, T2",kernel = "uniform",support=c(-100,100))

Active10=ifelse(Act3=="Active",1,0)

plot_grid(C$rdplot,
          T1$rdplot,
          T2$rdplot)
detach(MainDB)
attach(MainDB %>% filter(Assignment=="Control"))
p_load(binsreg)

Active10=ifelse(Act3=="Active",1,0)
rdrobust(x=RunningVar,y=ECSUseYes,covs = Active10) %>% summary()
rdrobust(x=RunningVar,y=UseCreche) %>% summary()

single10=ifelse(SingleMum==TRUE,1,0)
rdrobust(x=RunningVar,y=UseCreche,covs = Active10+High_SES) %>% summary()


binsreg(x=RunningVar,y=UseCreche, by=Assignment,line = c(3,3), ci=c(3,3), cb=c(3,3), polyreg=4) 

binreg <- binsreg(x=RunningVar,y=UseCreche, by=Assignment,line = c(3,3), ci=c(3,3), cb=c(3,3), polyreg=4) 

# Extract the plotting information
result <- binreg$data.plot$`Group Control`

# Create the figure to plot
fig <- ggplot() + labs(x='X',y ='Y')

# Add the dots
fig <- fig + geom_point(data=result$data.dots, aes(x=x, y=fit), color="blue", size=2, shape='o')

# Add the line
fig <- fig + geom_line(data=result$data.line, aes(x=x, y=fit), color="blue", size=0.5)

# Add the CI
fig <- fig + geom_errorbar(data=result$data.ci, aes(x=x, ymin=ci.l, ymax=ci.r), color="blue", size=0.5, width = 0.02, linetype='solid')

# Add the CB
fig <- fig + geom_ribbon(data=result$data.cb, aes(x=x, ymin=cb.l, ymax=cb.r), fill="blue", alpha=0.2)

# Add the polyreg
fig <- fig + geom_line(data=result$data.poly, aes(x=x, y=fit), color="blue", size=0.5)


# Extract the plotting information
resultT2 <- binreg$data.plot$`Group T2`

# Add the dots
fig <- fig + geom_point(data=resultT2$data.dots, aes(x=x, y=fit), color="red", size=2, shape='o')

# Add the line
fig <- fig + geom_line(data=resultT2$data.line, aes(x=x, y=fit), color="red", size=0.5)

# Add the CI
fig <- fig + geom_errorbar(data=resultT2$data.ci, aes(x=x, ymin=ci.l, ymax=ci.r), color="red", size=0.5, width = 0.02, linetype='solid')

# Add the CB
fig <- fig + geom_ribbon(data=resultT2$data.cb, aes(x=x, ymin=cb.l, ymax=cb.r), fill="red", alpha=0.2)

# Add the polyreg
fig <- fig + geom_line(data=resultT2$data.poly, aes(x=x, y=fit), color="red", size=0.5)






# Display the plot
print(fig)





binsreg(x=RunningVar,y=UseCreche, by=Assignment,line=c(3,3),dotsgrid=1, dotsgridmean=F, nbins=10, samebinsby=T)

w = NULL, data = NULL, at = NULL, deriv = 0,
  dots = NULL, dotsgrid = 0, dotsgridmean = T, line = NULL,
  linegrid = 20, ci = NULL, cigrid = 0, cigridmean = T, cb = NULL,
  cbgrid = 20, polyreg = NULL, polyreggrid = 20, polyregcigrid = 0,
  by = NULL, bycolors = NULL, bysymbols = NULL, bylpatterns = NULL,
  legendTitle = NULL, legendoff = F, nbins = NULL, binspos = "qs",
  binsmethod = "dpi", nbinsrot = NULL, pselect = NULL, sselect = NULL,
  samebinsby = F, randcut = NULL, nsims = 500, simsgrid = 20,
  simsseed = NULL, vce = "HC1", cluster = NULL, asyvar = F,
  level = 95, noplot = F, dfcheck = c(20, 30), masspoints = "on",
  weights = NULL, subset = NULL, plotxrange = NULL, plotyrange = NULL)

binsreg y x w, nbins(20) line(T) ci(T) cb(T) pselect(0/3)


detach(MainDB %>% filter(Assignment=="Control"))

attach(MainDB %>% filter(Assignment=="T1"))
rdrobust(x=RunningVar,y=ECSUseYes) %>% summary()
rdrobust(x=RunningVar,y=UseCreche) %>% summary()

detach(MainDB %>% filter(Assignment=="T1"))


attach(MainDB %>% filter(Assignment=="T2"))
rdrobust(x=RunningVar,y=ECSUseYes) %>% summary()
rdrobust(x=RunningVar,y=UseCreche) %>% summary()

detach(MainDB %>% filter(Assignment=="T2"))


feols(UseCreche~T2*I(RunningVar>0)|StrataWave,data=MainDB %>% filter(abs(RunningVar)<=30 & Assignment!="T1")) %>% etable()





```




